set(STM32_FAMILY stm32f7xx)
set(SOS_INCLUDE_DIRECTORIES include include/stm32 src ${STM32_FAMILY} include/stm32/cmsis)

file(GLOB STM32_FAMILY_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/${STM32_FAMILY}/*)
file(GLOB STM32_VARIANT_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/${STM32_VARIANT}/*.c")
file(GLOB STM32_VARIANT_HEADERS
	${CMAKE_CURRENT_SOURCE_DIR}/include/stm32/*${STM32_VARIANT}.h
	${CMAKE_CURRENT_SOURCE_DIR}/include/stm32/cmsis/${STM32_FAMILY}.h
	${CMAKE_CURRENT_SOURCE_DIR}/include/stm32/cmsis/${STM32_VARIANT}.h)
file(GLOB STM32_LDSCRIPT_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/ldscript/stm32f7*")
set(SOS_SOURCELIST ${SHARED_SOURCELIST} ${STM32_FAMILY_SOURCES} ${STM32_VARIANT_SOURCES} ${STM32_VARIANT_HEADERS} ${STM32_LDSCRIPT_SOURCES})
set(SOS_OPTION mcu_${STM32_VARIANT})
set(SOS_DEFINITIONS __${STM32_VARIANT} ${STM32_VARIANT_DEFINE}=1)

add_targets()

