set(STM32_FAMILY stm32f2xx)

file(GLOB STM32_FAMILY_SOURCES ${CMAKE_SOURCE_DIR}/src/${STM32_FAMILY}/*)
file(GLOB STM32_VARIANT_SOURCES "${CMAKE_SOURCE_DIR}/src/${STM32_VARIANT}/*.c")
file(GLOB STM32_VARIANT_HEADERS	${CMAKE_SOURCE_DIR}/include/*${STM32_VARIANT}.h ${CMAKE_SOURCE_DIR}/include/cmsis/${STM32_FAMILY}.h ${CMAKE_SOURCE_DIR}/include/cmsis/${STM32_VARIANT}.h)
file(GLOB STM32_LDSCRIPT_SOURCES "${CMAKE_SOURCE_DIR}/ldscript/stm32f2*")

set(SOS_SOURCELIST ${SHARED_SOURCELIST} ${STM32_FAMILY_SOURCES} ${STM32_VARIANT_SOURCES} ${STM32_VARIANT_HEADERS} ${STM32_LDSCRIPT_SOURCES})
set(SOS_DEFINITIONS __${STM32_VARIANT} ${STM32_VARIANT_DEFINE}=1)
set(SOS_INCLUDE_DIRECTORIES include src src/${STM32_FAMILY} ${STM32_FAMILY}  include/cmsis)

add_targets()
